before_install:
  - wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
  - sudo apt-get -y install software-properties-common
  - sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          update: true

          sources:
            - ubuntu-toolchain-r-test
          packages:
            - luarocks
            - openresty
            - libsqlite3-dev

install: true

language: generic

before_script:
  - sudo luarocks install busted

script: ./start -b
