language: generic

sudo: true

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          update: true

          sources:
            - ubuntu-toolchain-r-test
          packages:
            - luarocks
            - libsqlite3-dev

before_install:
  - wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
  - sudo apt-get -y install software-properties-common
  - sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
  - sudo apt-get update
  - sudo apt-get install -yq openresty
  - cd ..
  - wget -q https://download.libsodium.org/libsodium/releases/LATEST.tar.gz
  - tar -xf LATEST.tar.gz && cd libsodium-stable
  - ./configure
  - make && make check
  - sudo make install
  - cd ../lbry-comments

install: true

before_script:
  - sudo luarocks install busted
  - sudo luarocks install cluacov

script:
  - ./start -B

after_success:
  - bash <(curl -s https://codecov.io/bash)
