#!/bin/bash

THIS_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT_PATH="${THIS_PATH}/src/server.lua"

# for LuaJIT
EXEC0="_G.toppath=\"${THIS_PATH}\""
EXEC1="_G.srcpath=_G.toppath..\"/src\""
# for busted, as it has weird execution needs.
EXEC0b="_G.toppath=\\\"${THIS_PATH}\\\""
EXEC1b="_G.srcpath=_G.toppath..\\\"/src\\\""

mkdir -p ${THIS_PATH}/logs

while getopts ":bBhdDq" opt; do
	case $opt in
		b)
			busted -e "${EXEC0b}" -e "${EXEC1b}"
			exit 0
			;;
		B)
			busted -c -e "${EXEC0b}" -e "${EXEC1b}"
			exit 0
			;;
		d)
			ldoc ${THIS_PATH}
			exit 0
			;;
		D)
			ldoc -a ${THIS_PATH}
			exit 0
			;;
		q)
			openresty -p ${THIS_PATH} -s quit
			exit 0
			;;
		h)
			echo "Run with \"-b\" to run busted. Requires busted."
			echo "Run with \"-B\" to run busted with coverage. Requires busted and LuaCov."
			echo "Run with \"-d\" to generate the doc"
			echo "Run with \"-D\" to generate the doc, including local variables"
			echo "Run with \"-q\" to quit the server, if it's running"
			echo "Run with \"-h\" to print out the help"
			echo "Run without args to run normally"
			exit 0
			;;
		\?)
			echo "Invalid option: -$OPTARG"
			exit 1
			;;
	esac
done

openresty -p ${THIS_PATH}
